INSERT INTO STATUS VALUES (1, 'Open');
INSERT INTO STATUS VALUES (2, 'Close');
INSERT INTO STATUS VALUES (3, 'Reopen');
INSERT INTO STATUS VALUES (4, 'Investigation');
INSERT INTO STATUS VALUES (5, 'Development');