INSERT INTO STATUS VALUES (1, 'OPEN');
INSERT INTO STATUS VALUES (2, 'CLOSE');
INSERT INTO STATUS VALUES (3, 'REOPEN');
INSERT INTO STATUS VALUES (4, 'INVESTIGATION');
INSERT INTO STATUS VALUES (5, 'DEVELOPMENT');